// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package suigraphql

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/Khan/genqlient/graphql"
)

// Value includes the GraphQL fields of MoveValue requested by the fragment Value.
type Value struct {
	// The value's type.
	Type ValueTypeMoveType `json:"type"`
	// Representation of a Move value in JSON, where:
	//
	// - Addresses, IDs, and UIDs are represented in canonical form, as JSON strings.
	// - Bools are represented by JSON boolean literals.
	// - u8, u16, and u32 are represented as JSON numbers.
	// - u64, u128, and u256 are represented as JSON strings.
	// - Balances, Strings, and Urls are represented as JSON strings.
	// - Vectors of bytes are represented as Base64 blobs, and other vectors are represented by JSON arrays.
	// - Structs are represented by JSON objects.
	// - Enums are represented by JSON objects, with a field named `@variant` containing the variant name.
	// - Empty optional values are represented by `null`.
	Json json.RawMessage `json:"json"`
}

// GetType returns Value.Type, and is useful for accessing the field via an interface.
func (v *Value) GetType() ValueTypeMoveType { return v.Type }

// GetJson returns Value.Json, and is useful for accessing the field via an interface.
func (v *Value) GetJson() json.RawMessage { return v.Json }

// ValueTypeMoveType includes the requested fields of the GraphQL type MoveType.
// The GraphQL type's documentation follows.
//
// Represents instances of concrete types (no type parameters, no references).
type ValueTypeMoveType struct {
	// Flat representation of the type signature, as a displayable string.
	Repr string `json:"repr"`
}

// GetRepr returns ValueTypeMoveType.Repr, and is useful for accessing the field via an interface.
func (v *ValueTypeMoveType) GetRepr() string { return v.Repr }

// __getDynamicFieldsInput is used internally by genqlient
type __getDynamicFieldsInput struct {
	Id string `json:"id"`
}

// GetId returns __getDynamicFieldsInput.Id, and is useful for accessing the field via an interface.
func (v *__getDynamicFieldsInput) GetId() string { return v.Id }

// getDynamicFieldsAddress includes the requested fields of the GraphQL type Address.
type getDynamicFieldsAddress struct {
	// Dynamic fields owned by this address.
	//
	// The address must correspond to an object (account addresses cannot own dynamic fields), but that object may be wrapped.
	DynamicFields getDynamicFieldsAddressDynamicFieldsDynamicFieldConnection `json:"dynamicFields"`
}

// GetDynamicFields returns getDynamicFieldsAddress.DynamicFields, and is useful for accessing the field via an interface.
func (v *getDynamicFieldsAddress) GetDynamicFields() getDynamicFieldsAddressDynamicFieldsDynamicFieldConnection {
	return v.DynamicFields
}

// getDynamicFieldsAddressDynamicFieldsDynamicFieldConnection includes the requested fields of the GraphQL type DynamicFieldConnection.
type getDynamicFieldsAddressDynamicFieldsDynamicFieldConnection struct {
	// A list of nodes.
	Nodes []getDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicField `json:"nodes"`
}

// GetNodes returns getDynamicFieldsAddressDynamicFieldsDynamicFieldConnection.Nodes, and is useful for accessing the field via an interface.
func (v *getDynamicFieldsAddressDynamicFieldsDynamicFieldConnection) GetNodes() []getDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicField {
	return v.Nodes
}

// getDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicField includes the requested fields of the GraphQL type DynamicField.
// The GraphQL type's documentation follows.
//
// Dynamic fields are heterogenous fields that can be added or removed from an object at runtime. Their names are arbitrary Move values that have `copy`, `drop`, and `store`.
//
// There are two sub-types of dynamic fields:
//
// - Dynamic fields can store any value that has `store`. Objects stored in this kind of field will be considered wrapped (not accessible via its ID by external tools like explorers, wallets, etc. accessing storage).
// - Dynamic object fields can only store objects (values that have the `key` ability, and an `id: UID` as its first field) that have `store`, but they will still be directly accessible off-chain via their ID after being attached as a field.
type getDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicField struct {
	// The dynamic field's name, as a Move value.
	Name getDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldNameMoveValue `json:"name"`
	// The dynamic field's value, as a Move value for dynamic fields and as a MoveObject for dynamic object fields.
	Value getDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldValue `json:"-"`
}

// GetName returns getDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicField.Name, and is useful for accessing the field via an interface.
func (v *getDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicField) GetName() getDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldNameMoveValue {
	return v.Name
}

// GetValue returns getDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicField.Value, and is useful for accessing the field via an interface.
func (v *getDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicField) GetValue() getDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldValue {
	return v.Value
}

func (v *getDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicField) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*getDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicField
		Value json.RawMessage `json:"value"`
		graphql.NoUnmarshalJSON
	}
	firstPass.getDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicField = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	{
		dst := &v.Value
		src := firstPass.Value
		if len(src) != 0 && string(src) != "null" {
			err = __unmarshalgetDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldValue(
				src, dst)
			if err != nil {
				return fmt.Errorf(
					"unable to unmarshal getDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicField.Value: %w", err)
			}
		}
	}
	return nil
}

type __premarshalgetDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicField struct {
	Name getDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldNameMoveValue `json:"name"`

	Value json.RawMessage `json:"value"`
}

func (v *getDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicField) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *getDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicField) __premarshalJSON() (*__premarshalgetDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicField, error) {
	var retval __premarshalgetDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicField

	retval.Name = v.Name
	{

		dst := &retval.Value
		src := v.Value
		var err error
		*dst, err = __marshalgetDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldValue(
			&src)
		if err != nil {
			return nil, fmt.Errorf(
				"unable to marshal getDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicField.Value: %w", err)
		}
	}
	return &retval, nil
}

// getDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldNameMoveValue includes the requested fields of the GraphQL type MoveValue.
type getDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldNameMoveValue struct {
	Value `json:"-"`
}

// GetType returns getDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldNameMoveValue.Type, and is useful for accessing the field via an interface.
func (v *getDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldNameMoveValue) GetType() ValueTypeMoveType {
	return v.Value.Type
}

// GetJson returns getDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldNameMoveValue.Json, and is useful for accessing the field via an interface.
func (v *getDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldNameMoveValue) GetJson() json.RawMessage {
	return v.Value.Json
}

func (v *getDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldNameMoveValue) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*getDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldNameMoveValue
		graphql.NoUnmarshalJSON
	}
	firstPass.getDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldNameMoveValue = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	err = json.Unmarshal(
		b, &v.Value)
	if err != nil {
		return err
	}
	return nil
}

type __premarshalgetDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldNameMoveValue struct {
	Type ValueTypeMoveType `json:"type"`

	Json json.RawMessage `json:"json"`
}

func (v *getDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldNameMoveValue) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *getDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldNameMoveValue) __premarshalJSON() (*__premarshalgetDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldNameMoveValue, error) {
	var retval __premarshalgetDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldNameMoveValue

	retval.Type = v.Value.Type
	retval.Json = v.Value.Json
	return &retval, nil
}

// getDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldValue includes the requested fields of the GraphQL interface DynamicFieldValue.
//
// getDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldValue is implemented by the following types:
// getDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldValueMoveObject
// getDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldValueMoveValue
// The GraphQL type's documentation follows.
//
// The value of a dynamic field (`MoveValue`) or dynamic object field (`MoveObject`).
type getDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldValue interface {
	implementsGraphQLInterfacegetDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldValue()
	// GetTypename returns the receiver's concrete GraphQL type-name (see interface doc for possible values).
	GetTypename() string
}

func (v *getDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldValueMoveObject) implementsGraphQLInterfacegetDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldValue() {
}
func (v *getDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldValueMoveValue) implementsGraphQLInterfacegetDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldValue() {
}

func __unmarshalgetDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldValue(b []byte, v *getDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldValue) error {
	if string(b) == "null" {
		return nil
	}

	var tn struct {
		TypeName string `json:"__typename"`
	}
	err := json.Unmarshal(b, &tn)
	if err != nil {
		return err
	}

	switch tn.TypeName {
	case "MoveObject":
		*v = new(getDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldValueMoveObject)
		return json.Unmarshal(b, *v)
	case "MoveValue":
		*v = new(getDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldValueMoveValue)
		return json.Unmarshal(b, *v)
	case "":
		return fmt.Errorf(
			"response was missing DynamicFieldValue.__typename")
	default:
		return fmt.Errorf(
			`unexpected concrete type for getDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldValue: "%v"`, tn.TypeName)
	}
}

func __marshalgetDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldValue(v *getDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldValue) ([]byte, error) {

	var typename string
	switch v := (*v).(type) {
	case *getDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldValueMoveObject:
		typename = "MoveObject"

		result := struct {
			TypeName string `json:"__typename"`
			*getDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldValueMoveObject
		}{typename, v}
		return json.Marshal(result)
	case *getDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldValueMoveValue:
		typename = "MoveValue"

		premarshaled, err := v.__premarshalJSON()
		if err != nil {
			return nil, err
		}
		result := struct {
			TypeName string `json:"__typename"`
			*__premarshalgetDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldValueMoveValue
		}{typename, premarshaled}
		return json.Marshal(result)
	case nil:
		return []byte("null"), nil
	default:
		return nil, fmt.Errorf(
			`unexpected concrete type for getDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldValue: "%T"`, v)
	}
}

// getDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldValueMoveObject includes the requested fields of the GraphQL type MoveObject.
// The GraphQL type's documentation follows.
//
// A MoveObject is a kind of Object that reprsents data stored on-chain.
type getDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldValueMoveObject struct {
	Typename string `json:"__typename"`
	// The structured representation of the object's contents.
	Contents getDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldValueMoveObjectContentsMoveValue `json:"contents"`
}

// GetTypename returns getDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldValueMoveObject.Typename, and is useful for accessing the field via an interface.
func (v *getDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldValueMoveObject) GetTypename() string {
	return v.Typename
}

// GetContents returns getDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldValueMoveObject.Contents, and is useful for accessing the field via an interface.
func (v *getDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldValueMoveObject) GetContents() getDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldValueMoveObjectContentsMoveValue {
	return v.Contents
}

// getDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldValueMoveObjectContentsMoveValue includes the requested fields of the GraphQL type MoveValue.
type getDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldValueMoveObjectContentsMoveValue struct {
	Value `json:"-"`
}

// GetType returns getDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldValueMoveObjectContentsMoveValue.Type, and is useful for accessing the field via an interface.
func (v *getDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldValueMoveObjectContentsMoveValue) GetType() ValueTypeMoveType {
	return v.Value.Type
}

// GetJson returns getDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldValueMoveObjectContentsMoveValue.Json, and is useful for accessing the field via an interface.
func (v *getDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldValueMoveObjectContentsMoveValue) GetJson() json.RawMessage {
	return v.Value.Json
}

func (v *getDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldValueMoveObjectContentsMoveValue) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*getDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldValueMoveObjectContentsMoveValue
		graphql.NoUnmarshalJSON
	}
	firstPass.getDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldValueMoveObjectContentsMoveValue = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	err = json.Unmarshal(
		b, &v.Value)
	if err != nil {
		return err
	}
	return nil
}

type __premarshalgetDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldValueMoveObjectContentsMoveValue struct {
	Type ValueTypeMoveType `json:"type"`

	Json json.RawMessage `json:"json"`
}

func (v *getDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldValueMoveObjectContentsMoveValue) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *getDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldValueMoveObjectContentsMoveValue) __premarshalJSON() (*__premarshalgetDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldValueMoveObjectContentsMoveValue, error) {
	var retval __premarshalgetDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldValueMoveObjectContentsMoveValue

	retval.Type = v.Value.Type
	retval.Json = v.Value.Json
	return &retval, nil
}

// getDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldValueMoveValue includes the requested fields of the GraphQL type MoveValue.
type getDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldValueMoveValue struct {
	Typename string `json:"__typename"`
	Value    `json:"-"`
}

// GetTypename returns getDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldValueMoveValue.Typename, and is useful for accessing the field via an interface.
func (v *getDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldValueMoveValue) GetTypename() string {
	return v.Typename
}

// GetType returns getDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldValueMoveValue.Type, and is useful for accessing the field via an interface.
func (v *getDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldValueMoveValue) GetType() ValueTypeMoveType {
	return v.Value.Type
}

// GetJson returns getDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldValueMoveValue.Json, and is useful for accessing the field via an interface.
func (v *getDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldValueMoveValue) GetJson() json.RawMessage {
	return v.Value.Json
}

func (v *getDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldValueMoveValue) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*getDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldValueMoveValue
		graphql.NoUnmarshalJSON
	}
	firstPass.getDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldValueMoveValue = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	err = json.Unmarshal(
		b, &v.Value)
	if err != nil {
		return err
	}
	return nil
}

type __premarshalgetDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldValueMoveValue struct {
	Typename string `json:"__typename"`

	Type ValueTypeMoveType `json:"type"`

	Json json.RawMessage `json:"json"`
}

func (v *getDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldValueMoveValue) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *getDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldValueMoveValue) __premarshalJSON() (*__premarshalgetDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldValueMoveValue, error) {
	var retval __premarshalgetDynamicFieldsAddressDynamicFieldsDynamicFieldConnectionNodesDynamicFieldValueMoveValue

	retval.Typename = v.Typename
	retval.Type = v.Value.Type
	retval.Json = v.Value.Json
	return &retval, nil
}

// getDynamicFieldsResponse is returned by getDynamicFields on success.
type getDynamicFieldsResponse struct {
	// Look-up an account by its SuiAddress.
	//
	// If `rootVersion` is specified, nested dynamic field accesses will be fetched at or before this version. This can be used to fetch a child or ancestor object bounded by its root object's version, when its immediate parent is wrapped, or a value in a dynamic object field. For any wrapped or child (object-owned) object, its root object can be defined recursively as:
	//
	// - The root object of the object it is wrapped in, if it is wrapped.
	// - The root object of its owner, if it is owned by another object.
	// - The object itself, if it is not object-owned or wrapped.
	//
	// Specifying a `rootVersion` disables nested queries for paginating owned objects or dynamic fields (these queries are only supported at checkpoint boundaries).
	Address getDynamicFieldsAddress `json:"address"`
}

// GetAddress returns getDynamicFieldsResponse.Address, and is useful for accessing the field via an interface.
func (v *getDynamicFieldsResponse) GetAddress() getDynamicFieldsAddress { return v.Address }

// The query executed by getDynamicFields.
const getDynamicFields_Operation = `
query getDynamicFields ($id: SuiAddress!) {
	address(address: $id) {
		dynamicFields {
			nodes {
				name {
					... Value
				}
				value {
					__typename
					... on MoveValue {
						... Value
					}
					... on MoveObject {
						contents {
							... Value
						}
					}
				}
			}
		}
	}
}
fragment Value on MoveValue {
	type {
		repr
	}
	json
}
`

func getDynamicFields(
	ctx_ context.Context,
	client_ graphql.Client,
	id string,
) (data_ *getDynamicFieldsResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "getDynamicFields",
		Query:  getDynamicFields_Operation,
		Variables: &__getDynamicFieldsInput{
			Id: id,
		},
	}

	data_ = &getDynamicFieldsResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}
